{
 "title": "Apache IoTDB Performance Overview Dashboard",
 "description": "Performance Overview Dashboard of Apache IoTDB",
 "tags": [
  "Apache IoTDB",
  "v1.1"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "nodeType",
    "query": {
     "query": "label_values({cluster=~\"$cluster\"},nodeType)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({cluster=~\"$cluster\",nodeType=~\"$nodeType\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Core(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sys_cpu_cores{cluster=~\"$cluster\", nodeType=~\"$nodeType\", name=\"system\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sys_disk_total_space{cluster=~\"$cluster\", nodeType=~\"$nodeType\", name=\"system\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Timeseries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quantity{cluster=~\"$cluster\", nodeType=~\"$nodeType\", name=\"timeSeries\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cluster System Overview",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(process_total_mem{cluster=~\"$cluster\", nodeType=~\"$nodeType\"}) - sum(process_free_mem{cluster=~\"$cluster\", nodeType=~\"$nodeType\"})) / sum(sys_total_physical_memory_size{cluster=~\"$cluster\", nodeType=~\"$nodeType\", name=\"system\"})",
     "legendFormat": "Average DataNode Memory Usage"
    },
    {
     "expr": "1- sum(sys_disk_free_space{cluster=~\"$cluster\", nodeType=~\"$nodeType\"}) / sum(sys_disk_total_space{cluster=~\"$cluster\", nodeType=~\"$nodeType\"})",
     "legendFormat": "Average Disk Usage"
    }
   ]
  },
  {
   "title": "Total Write Point Per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(quantity_total{cluster=~\"$cluster\", nodeType=~\"$nodeType\"}[1m]))",
     "legendFormat": "Total Points"
    }
   ]
  },
  {
   "title": "Total System Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sys_total_physical_memory_size{cluster=~\"$cluster\", nodeType=~\"$nodeType\", name=\"system\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Swap Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sys_total_swap_space_size{cluster=~\"$cluster\", nodeType=~\"$nodeType\", name=\"system\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total File Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(file_count{cluster=~\"$cluster\", nodeType=~\"$nodeType\", name!=\"open_file_handlers\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DataNode CPU Load",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_load{cluster=~\"$cluster\", nodeType=\"$nodeType\"}/100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DataNode Process Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(process_total_mem{cluster=~\"$cluster\", nodeType=~\"$nodeType\"}) by (instance) - sum(process_free_mem{cluster=~\"$cluster\", nodeType=~\"$nodeType\"}) by (instance)) / sum(sys_total_physical_memory_size{cluster=~\"$cluster\", nodeType=~\"$nodeType\", name=\"system\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DataNode Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sys_disk_free_space{cluster=~\"$cluster\", nodeType=\"$nodeType\"} / sys_disk_total_space{cluster=~\"$cluster\", nodeType=\"$nodeType\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Overview $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Core",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Core(s)" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sys_cpu_cores{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "$instance"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sys_disk_total_space{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Timeseries",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantity{instance=~\"$instance\", name=\"timeSeries\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "System Overview",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_cpu_load{instance=~\"$instance\"} / 100",
       "legendFormat": "CPU Load"
      },
      {
       "expr": "(sum(process_total_mem{instance=~\"$instance\"}) - sum(process_free_mem{instance=~\"$instance\"})) / sum(sys_total_physical_memory_size{instance=~\"$instance\", name=\"system\"})",
       "legendFormat": "Process Memory Usage"
      },
      {
       "expr": "1- sys_disk_free_space{instance=~\"$instance\"} / sys_disk_total_space{instance=~\"$instance\"}",
       "legendFormat": "Disk Usage"
      }
     ]
    },
    {
     "title": "Write Point Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 2 },
     "targets": [
      {
       "expr": "rate(quantity_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "$instance"
      }
     ]
    },
    {
     "title": "System Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sys_total_physical_memory_size{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Swap Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sys_total_swap_space_size{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "File Number",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(file_count{instance=~\"$instance\", name!=\"open_file_handlers\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Session Idle Time $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(rate(session_idle_time_sum{instance=~\"$instance\"}[1m])) / sum(rate(session_idle_time_count{instance=~\"$instance\"}[1m]))",
       "legendFormat": "Average Idle"
      },
      {
       "expr": "sum(rate(performance_overview_seconds_sum{instance=~\"$instance\"}[1m])) / sum(rate(performance_overview_seconds_count{instance=~\"$instance\"}[1m])) * 1000000000",
       "legendFormat": "Average Busy"
      }
     ]
    },
    {
     "title": "Client Connection $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "thrift_connections{instance=~\"$instance\", name=~\".*Client.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "thrift_active_threads{instance=~\"$instance\", name=~\".*Client.*\"}",
       "legendFormat": "Active"
      }
     ]
    },
    {
     "title": "Time Consumed Of Operation $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "performance_overview_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "{{type}} - {{interface}} - 99"
      },
      {
       "expr": "sum(rate(performance_overview_seconds_sum{instance=~\"$instance\"}[1m]) / rate(performance_overview_seconds_count{instance=~\"$instance\"}[1m])) by (instance, interface, type)",
       "legendFormat": "{{type}} - {{interface}} - avg"
      }
     ]
    },
    {
     "title": "Average Time Consumed Of Interface $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(entry_seconds_sum{instance=~\"$instance\"}[1m]) / rate(entry_seconds_count{instance=~\"$instance\"}[1m])) by (instance, name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "P99 Time Consumed Of Interface $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "entry_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Task Number $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "queue{instance=~\"$instance\"}",
       "legendFormat": "{{name}}-{{status}}"
      }
     ]
    },
    {
     "title": "Average Time Consumed of Task $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(cost_task_seconds_sum{instance=~\"$instance\"}[1m])/rate(cost_task_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "P99 Time Consumed of Task $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cost_task_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "OPS $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 41 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(performance_overview_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "operation {{type}} {{interface}}"
      },
      {
       "expr": "rate(entry_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "rpc {{name}}"
      }
     ]
    },
    {
     "title": "OPS Of Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 41 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(performance_overview_detail_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "OPS Of Schedule $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 41 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(performance_overview_schedule_detail_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "OPS Of Local Schedule Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(performance_overview_local_detail_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "OPS Of Storage Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(performance_overview_storage_detail_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{stage}}"
      },
      {
       "expr": "rate(performance_overview_storage_detail_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "consensus"
      }
     ]
    },
    {
     "title": "OPS Of Engine Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(performance_overview_engine_detail_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Average Time Consumed Of Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(performance_overview_detail_seconds_sum{instance=~\"$instance\"}[1m]) / rate(performance_overview_detail_seconds_count{instance=~\"$instance\"}[1m])) by (instance, stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Average Time Consumed Of Schedule Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(performance_overview_schedule_detail_seconds_sum{instance=~\"$instance\"}[1m]) / rate(performance_overview_schedule_detail_seconds_count{instance=~\"$instance\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": " Average Time Consumed Of Local Schedule Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(performance_overview_local_detail_seconds_sum{instance=~\"$instance\"}[1m]) / rate(performance_overview_local_detail_seconds_count{instance=~\"$instance\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Average Time Consumed Of Storage Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "abs(sum(rate(performance_overview_local_detail_seconds_sum{instance=~\"$instance\", stage=\"storage\"}[1m])) - sum(rate(performance_overview_storage_detail_seconds_sum{instance=~\"$instance\", stage=\"engine\"}[1m]))) / sum(rate(performance_overview_storage_detail_seconds_count{instance=~\"$instance\", stage=\"engine\"}[1m]))",
       "legendFormat": "consensus"
      },
      {
       "expr": "rate(performance_overview_storage_detail_seconds_sum{instance=~\"$instance\", stage=\"engine\"}[1m]) / rate(performance_overview_storage_detail_seconds_count{instance=~\"$instance\", stage=\"engine\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Average Time Consumed Of Engine Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(performance_overview_engine_detail_seconds_sum{instance=~\"$instance\"}[1m]) / rate(performance_overview_engine_detail_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "P99 Time Consumed Of Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "performance_overview_detail_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "P99 Time Consumed Of Schedule Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "performance_overview_schedule_detail_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "P99 Time Consumed Of Local Schedule Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "performance_overview_local_detail_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "P99 Time Consumed Of Storage Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(performance_overview_local_detail_seconds{instance=~\"$instance\", quantile=\"0.99\", stage=\"storage\"}) - sum(performance_overview_storage_detail_seconds{instance=~\"$instance\", quantile=\"0.99\", stage=\"engine\"})",
       "legendFormat": "consensus"
      },
      {
       "expr": "performance_overview_storage_detail_seconds{instance=~\"$instance\", quantile=\"0.99\", stage=\"engine\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "P99 Time Consumed Of Engine Stage $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "performance_overview_engine_detail_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "{{stage}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Load $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sys_cpu_load{instance=~\"$instance\",name=\"system\"}",
       "legendFormat": "System CPU Load"
      },
      {
       "expr": "process_cpu_load{instance=~\"$instance\",name=\"process\"}",
       "legendFormat": "Process CPU Load"
      }
     ]
    },
    {
     "title": "CPU Time Per Minute $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_time{instance=~\"$instance\", name=\"process\"}[1m]))*60",
       "legendFormat": "System CPU Load"
      }
     ]
    },
    {
     "title": "GC Time Per Minute $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))*60",
       "legendFormat": "Young GC"
      },
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m]))*60",
       "legendFormat": "Full GC"
      }
     ]
    },
    {
     "title": "Heap Memory $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Maximum heap memory"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Used heap memory"
      },
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\", area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Off Heap Memory $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{instance=~\"$instance\"})",
       "legendFormat": "off heap memory"
      }
     ]
    },
    {
     "title": "The Number Of Java Thread $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
       "legendFormat": "total"
      },
      {
       "expr": "jvm_threads_states_threads{instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "File Count $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "file_count{instance=~\"$instance\",name!=\"open_file_handlers\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(file_count{instance=~\"$instance\", name!=\"open_file_handlers\"})",
       "legendFormat": "all"
      }
     ]
    },
    {
     "title": "File Size $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "file_size{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(file_size{instance=~\"$instance\"})",
       "legendFormat": "all"
      }
     ]
    },
    {
     "title": "Log Number Per Minute $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{instance=~\"${instance}\"}[1m])) by (level) * 60",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  }
 ]
}