{
 "title": "Apache IoTDB System Dashboard",
 "tags": [
  "Apache IoTDB",
  "v1.2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "nodeType",
    "query": {
     "query": "label_values({cluster=~\"$cluster\"},nodeType)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({cluster=~\"$cluster\",nodeType=~\"$nodeType\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Core $instance",
   "type": "stat",
   "description": "$instance 节点所在机器的 CPU 核数",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "Core(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_cpu_cores{instance=~\"$instance\",name=\"system\"}"
    }
   ]
  },
  {
   "title": "CPU Load $instance",
   "type": "timeseries",
   "description": "$instance 节点所在机器的 CPU 负载，包括系统 CPU 负载和 IoTDB 进程 CPU 负载",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_cpu_load{instance=~\"$instance\",name=\"system\"}",
     "legendFormat": "System"
    },
    {
     "expr": "process_cpu_load{instance=~\"$instance\",name=\"process\"}",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "CPU Time Per Minute $instance",
   "type": "timeseries",
   "description": "$instance 节点所在机器的每分钟 CPU 时间，最大值和 CPU 核数有关",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time{instance=~\"$instance\", name=\"process\"}[1m]))*60",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Thread Pool CPU Load $instance",
   "type": "timeseries",
   "description": "$instance 节点各线程池的 CPU 负载",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pool_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Module CPU Load $instance",
   "type": "timeseries",
   "description": "$instance 节点各模块的 CPU 负载",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "module_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Thread Pool User Time Percentage $instance",
   "type": "timeseries",
   "description": "$instance 节点各线程池的用户态时间占比",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "user_time_percentage{instance=~\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Module User Time Percentage $instance",
   "type": "timeseries",
   "description": "$instance 节点各模块用户态时间占比",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "module_user_time_percentage{instance=~\"$instance\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Thread Pool Active Thread Count $instance",
   "type": "timeseries",
   "description": "$instance 节点各线程池的活跃线程数量",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 169 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "thread_pool_active_thread_count{instance=~\"$instance\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Thread Pool Core Size $instance",
   "type": "timeseries",
   "description": "$instance 节点各线程池核心线程数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "thread_pool_core_size{instance=~\"$instance\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Thread Pool Largest Pool Size $instance",
   "type": "timeseries",
   "description": "$instance 节点各线程池最大线程池数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "thread_pool_largest_pool_size{instance=~\"$instance\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Thread Pool Waiting Task Count $instance",
   "type": "timeseries",
   "description": "$instance 节点各线程池的等待任务数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 274 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "thread_pool_waiting_task_count{instance=~\"$instance\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": " Thread Pool Done Task Count Per Second $instance",
   "type": "timeseries",
   "description": "$instance 节点各线程池的每秒完成任务数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 274 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "rate(thread_pool_done_task_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 330 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Memory $instance",
     "type": "timeseries",
     "description": "$instance 节点的系统内存使用情况，包括系统可用物理内存大小、系统已经使用的内存大小和操作系统分配给正在运行的进程使用的虚拟内存的大小",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sys_total_physical_memory_size{instance=~\"$instance\", name=\"system\"}-sys_free_physical_memory_size{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "Used physical memory"
      },
      {
       "expr": "sys_total_physical_memory_size{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "Total physical memory"
      },
      {
       "expr": "sys_committed_vm_size{instance=~\"$instance\"}",
       "legendFormat": "Committed vm size"
      }
     ]
    },
    {
     "title": "System Swap Memory $instance",
     "type": "timeseries",
     "description": "$instance 节点系统交换空间内存使用情况，包括总交换区内存大小和已使用交换区内存大小",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sys_total_swap_space_size{instance=~\"$instance\", name=\"system\"} - sys_free_swap_space_size{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "Used Swap"
      },
      {
       "expr": "sys_total_swap_space_size{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "Total Swap Size"
      }
     ]
    },
    {
     "title": "Process Memory $instance",
     "type": "timeseries",
     "description": "$instance 节点 IoTDB 进程内存使用情况，包括进程最大可申请内存大小、进程已申请的可用内存大小、进程已用内存大小",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_max_mem{instance=~\"${instance}\"}",
       "legendFormat": "Max Memory"
      },
      {
       "expr": "process_total_mem{instance=~\"${instance}\"}",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "process_total_mem{instance=~\"${instance}\"} - process_free_mem{instance=~\"${instance}\"}",
       "legendFormat": "Used Memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 331 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space $instance",
     "type": "timeseries",
     "description": "$instance 节点的磁盘使用情况，包括可用最大磁盘空间大小和已用磁盘空间大小",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sys_disk_total_space{instance=~\"$instance\", name=\"system\"}-sys_disk_free_space{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "Used disk space"
      },
      {
       "expr": "sys_disk_total_space{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "Total disk space"
      }
     ]
    },
    {
     "title": "Log Number Per Minute $instance",
     "type": "timeseries",
     "description": "$instance 节点每分钟 IoTDB 各级别日志产生数量，包括error、warn、info、debug 和 trace 五个级别",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{instance=~\"${instance}\"}[1m])) by (level) * 60",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "File Count $instance",
     "type": "timeseries",
     "description": "$instance 节点管理的各类文件数量",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "file_count{instance=~\"$instance\",name!=\"open_file_handlers\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(file_count{instance=~\"$instance\", name!=\"open_file_handlers\"})",
       "legendFormat": "all"
      }
     ]
    },
    {
     "title": "Open File Count $instance",
     "type": "timeseries",
     "description": "$instance 节点打开的文件句柄数量",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "file_count{instance=~\"$instance\", name=\"open_file_handlers\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "File Size $instance",
     "type": "timeseries",
     "description": "$instance 节点管理的各类文件大小",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "file_size{instance=~\"$instance\",name!=\"open_file_handlers\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(file_size{instance=~\"$instance\", name!=\"open_file_handlers\"})",
       "legendFormat": "all"
      }
     ]
    },
    {
     "title": "Disk I/O Busy Rate $instance",
     "type": "timeseries",
     "description": "$instance 节点的各磁盘繁忙程度，等价于 iostat 里的 %util 指标，子项为各磁盘对应的指标",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "disk_io_busy_percentage{instance=~\"$instance\"}",
       "legendFormat": "{{disk_id}}"
      }
     ]
    },
    {
     "title": "Disk I/O Throughput $instance",
     "type": "timeseries",
     "description": "$instance 节点各磁盘在一段时间内 I/O Throughput 的平均值，读和写分开，子项为各磁盘对应的指标",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rate(disk_io_size{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{disk_id}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk I/O Ops $instance",
     "type": "timeseries",
     "description": "$instance 节点各磁盘每秒钟进行 I/O 的次数，等价于 iosta 中的 r/s, w/s, rrqm/s, wrqm/s。read 和 write 指磁盘执行单次 I/O 的次数，由于块设备有对应的调度算法，某些情况下将多个相邻操作的I/O合并为一次及逆行，merged-read 和 merged-write 表示多个 I/O 合并为一个 I/O 的次数，子项为各磁盘对应的指标",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(disk_io_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{disk_id}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk Per I/O Avg Time $instance",
     "type": "timeseries",
     "description": "$instance 节点各磁盘的每个 I/O 请求的平均时延，等价于 iostat 的 await，读和写分别统计，子项为各磁盘对应的指标",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 195 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "disk_io_avg_time{instance=~\"$instance\"}",
       "legendFormat": "{{disk_id}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk I/O Avg Size $instance",
     "type": "timeseries",
     "description": "$instance 节点各磁盘的每个 I/O 请求的大小，等价于 iostat 中的 avgrq-sz，读和写分开记录，子项为各磁盘对应的指标",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 195 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_io_avg_size{instance=~\"$instance\"}",
       "legendFormat": "{{disk_id}}-{{type}}"
      }
     ]
    },
    {
     "title": "Disk I/O Avg Queue $instance",
     "type": "timeseries",
     "description": "$instance 节点个磁盘 I/O 请求队列的平均长度，子项为各磁盘对应的指标",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 195 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "disk_io_avg_queue_size{instance=~\"$instance\"}",
       "legendFormat": "{{disk_id}}"
      }
     ]
    },
    {
     "title": "Process I/O Throughput $instance",
     "type": "timeseries",
     "description": "$instance 节点 IoTDB 进程的 I/O 吞吐量，分为 actual_read/write 和 attempt_read/write 两类。actual_read/write 表示进程实际调用块设备进行 I/O 的字节数，不包括 Page Cache 处理的部分",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 243 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rate(process_io_size{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{from}}-{{name}}"
      }
     ]
    },
    {
     "title": "Process I/O System Call Rate $instance",
     "type": "timeseries",
     "description": "$instance 节点 IoTDB 进程调用读写系统调用的速率",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 243 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(process_io_ops{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{from}}-{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 332 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Time Percentage $instance",
     "type": "timeseries",
     "description": "$instance 节点 JVM 在过去一分钟的时间窗口内，GC 耗时所占的比例",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "jvm_gc_accumulated_time_percentage{instance=~\"$instance\"}",
       "legendFormat": "GC Time Percentage"
      }
     ]
    },
    {
     "title": "GC Allocated/Promoted Size Detail $instance",
     "type": "timeseries",
     "description": "$instance 节点 JVM 平均每分钟晋升到老年代的对象大小，新生代/老年代和非分代新申请的对象大小",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_young_memory_allocated_bytes_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "Young-Allocated Object Size"
      },
      {
       "expr": "increase(jvm_gc_memory_promoted_bytes_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "Old-Promoted Object Size"
      },
      {
       "expr": "increase(jvm_gc_old_memory_allocated_bytes_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "Old-Allocated Object Size"
      },
      {
       "expr": "increase(jvm_gc_non_gen_memory_allocated_bytes_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "NonGen-Allocated Object Size"
      }
     ]
    },
    {
     "title": "GC Data Size Detail $instance",
     "type": "timeseries",
     "description": "$instance 节点 JVM 长期存活的对象大小和对应代际允许的最大值",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_gc_live_data_size_bytes{instance=~\"$instance\"}",
       "legendFormat": "Live Data Size"
      },
      {
       "expr": "jvm_gc_max_data_size_bytes{instance=~\"$instance\"}",
       "legendFormat": "Max Data Size"
      }
     ]
    },
    {
     "title": "Heap Memory $instance",
     "type": "timeseries",
     "description": "$instance 节点堆内存使用情况，包括 JVM 最大可用的堆内存大小、JVM 已提交的堆内存大小、JVM 已用的堆内存使用情况和各个内存区域的堆内存大小",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Maximum heap memory"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Used heap memory"
      },
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\", area=\"heap\"}",
       "legendFormat": "{{id}}"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Committed heap memory"
      }
     ]
    },
    {
     "title": "Off Heap Memory $instance",
     "type": "timeseries",
     "description": "$instance 节点堆外内存使用情况",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\", area=\"nonheap\"}",
       "legendFormat": "{{id}}"
      },
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{id}} memory"
      }
     ]
    },
    {
     "title": "GC Number Per Minute $instance",
     "type": "timeseries",
     "description": "$instance 节点 JVM 平均每分钟进行垃圾回收的次数，包括 YGC 和 FGC",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of major GC\"}[1m]))",
       "legendFormat": "Full GC"
      },
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))",
       "legendFormat": "Young GC"
      }
     ]
    },
    {
     "title": "GC Time Per Minute $instance",
     "type": "timeseries",
     "description": "$instance 节点 JVM 平均每分钟进行垃圾回收的耗时，包括 YGC 和 FGC",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))",
       "legendFormat": "Young GC"
      },
      {
       "expr": "sum(increase(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m]))",
       "legendFormat": "Full GC"
      },
      {
       "expr": "sum(increase(jvm_gc_concurrent_phase_time_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m]))",
       "legendFormat": "Full GC"
      },
      {
       "expr": "sum(increase(jvm_gc_concurrent_phase_time_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m]))",
       "legendFormat": "Young GC"
      }
     ]
    },
    {
     "title": "GC Number Per Minute Detail $instance",
     "type": "timeseries",
     "description": "$instance 节点 JVM 平均每分钟由于不同 cause 进行垃圾回收的次数，包括 YGC 和 FGC",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of major GC\"}[1m])",
       "legendFormat": "FullGC-{{cause}}"
      },
      {
       "expr": "increase(jvm_gc_pause_seconds_count{instance=~\"$instance\", action=\"end of minor GC\"}[1m])",
       "legendFormat": "YoungGC-{{cause}}"
      }
     ]
    },
    {
     "title": "GC Time Per Minute Detail $instance",
     "type": "timeseries",
     "description": "$instance 节点 JVM 平均每分钟由于不同 cause 进行垃圾回收的耗时，包括 YGC 和 FGC",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of major GC\"}[1m])",
       "legendFormat": "FullGC-{{cause}}"
      },
      {
       "expr": "increase(jvm_gc_pause_seconds_sum{instance=~\"$instance\", action=\"end of minor GC\"}[1m])",
       "legendFormat": "YoungGC-{{cause}}"
      },
      {
       "expr": "increase(jvm_gc_concurrent_phase_time_seconds_count{instance=~\"$instance\", action=\"end of major GC\"}[1m])",
       "legendFormat": "FullGC-{{cause}}"
      },
      {
       "expr": "increase(jvm_gc_concurrent_phase_time_seconds_count{instance=~\"$instance\", action=\"end of major GC\"}[1m])",
       "legendFormat": "YoungGC-{{cause}}"
      }
     ]
    },
    {
     "title": "Time Consumed Of Compilation Per Minute $instance",
     "type": "timeseries",
     "description": "$instance 节点 JVM 平均每分钟用于编译的总时间",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 196 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_compilation_time_ms{instance=~\"${instance}\"}[1m]))*60",
       "legendFormat": "compiler"
      }
     ]
    },
    {
     "title": "The Number Of Class $instance",
     "type": "timeseries",
     "description": "$instance 节点 JVM 加载和卸载类的数量情况",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 196 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_classes_unloaded_classes{instance=~\"$instance\"}",
       "legendFormat": "unloaded class"
      },
      {
       "expr": "jvm_classes_loaded_classes{instance=~\"$instance\"}",
       "legendFormat": "loaded class"
      }
     ]
    },
    {
     "title": "The Number Of Java Thread $instance",
     "type": "timeseries",
     "description": "$instance 节点 JVM 目前存活的线程情况，子项为处于不同状态的线程数",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 196 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
       "legendFormat": "total"
      },
      {
       "expr": "jvm_threads_states_threads{instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 333 },
   "collapsed": true,
   "panels": [
    {
     "title": "Net Speed $instance",
     "type": "timeseries",
     "description": "$instance 节点网卡发送和接收数据的速度，其中 eno 是连接公网网卡，io是虚拟网卡",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(received_bytes{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{iface_name}}-{{type}}"
      },
      {
       "expr": "rate(transmitted_bytes{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{iface_name}}-{{type}}"
      }
     ]
    },
    {
     "title": "Packet Speed $instance",
     "type": "timeseries",
     "description": "$instance 节点网卡每秒钟发送或接收的数据包大小，从系统重启后算起，其中 eno 是连接公网网卡，io是虚拟网卡",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(received_packets{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{iface_name}}-{{type}}"
      },
      {
       "expr": "rate(transmitted_packets{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{iface_name}}-{{type}}"
      }
     ]
    },
    {
     "title": "Receive/Transmit Data Size $instance",
     "type": "timeseries",
     "description": "$instance 节点网卡发送和接收数据包的速度，一次 RPC 请求可能对应一个或者多个数据包，其中 eno 是连接公网网卡，io是虚拟网卡",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "received_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{iface_name}}-{{type}}"
      },
      {
       "expr": "transmitted_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{iface_name}}-{{type}}"
      }
     ]
    },
    {
     "title": "Connection Num $instance",
     "type": "timeseries",
     "description": "$instance 节点 IoTDB 进程的 socket 连接数量，IoTDB 目前只有 TCP",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "connection_num{instance=~\"$instance\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}