{
 "title": "Apache IoTDB ConfigNode Dashboard",
 "tags": [
  "Apache IoTDB",
  "v1.1"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "nodeType",
    "query": {
     "query": "label_values({cluster=~\"$cluster\"}, nodeType)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({cluster=~\"$cluster\",nodeType=~\"$nodeType\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Overview $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Database Count",
     "type": "stat",
     "description": "The number of cluster Databases",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "database_num{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DataRegion Count",
     "type": "stat",
     "description": "The number of cluster DataRegions",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(region_num{type=\"DataRegion\", instance=~\"$instance\"}) by (type) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SchemaRegion Count",
     "type": "stat",
     "description": "The number of cluster SchemaRegions",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(region_num{type=\"SchemaRegion\", instance=~\"$instance\"}) by(type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "System Memory",
     "type": "stat",
     "description": "The system memory of current ConfigNode",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sys_total_physical_memory_size{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Swap Memory",
     "type": "stat",
     "description": "The swap memory of current ConfigNode",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sys_total_swap_space_size{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ConfigNodes",
     "type": "piechart",
     "description": "The current status of cluster ConfigNodes",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_num{instance=~\"$instance\", type=\"ConfigNode\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "DataNodes",
     "type": "piechart",
     "description": "The current status of cluster DataNodes",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_num{instance=~\"$instance\", type=\"DataNode\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "SchemaRegion Current Status",
     "type": "piechart",
     "description": "The current status of cluster SchemaRegions",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "region_num{type=\"SchemaRegion\", instance=~\"$instance\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "DataRegion Current Status",
     "type": "piechart",
     "description": "The current status of cluster DataRegions",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "region_num{type=\"DataRegion\", instance=~\"$instance\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "System Overview",
     "type": "bargauge",
     "description": "Bar of current ConfigNode",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1 - sys_free_physical_memory_size{instance=~\"$instance\", name=\"system\"} / sys_total_physical_memory_size{instance=~\"$instance\", name=\"system\"}",
       "legendFormat": "System Memory"
      },
      {
       "expr": "1 - sys_disk_free_space{instance=~\"$instance\"} / sys_disk_total_space{instance=~\"$instance\"}",
       "legendFormat": "Disk"
      },
      {
       "expr": "(sum(process_total_mem{instance=~\"$instance\"}) - sum(process_free_mem{instance=~\"$instance\"})) / sum(sys_total_physical_memory_size{instance=~\"$instance\", name=\"system\"})",
       "legendFormat": "Process Memory"
      },
      {
       "expr": "process_cpu_load{instance=~\"$instance\"} / 100",
       "legendFormat": "Cpu Load"
      }
     ]
    }
   ]
  },
  {
   "title": "NodeInfo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node Count $instance",
     "type": "timeseries",
     "description": "The number of cluster ConfigNodes",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 2 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "sum(node_num{instance=~\"$instance\"}) by(type) ",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "ConfigNode Status $instance",
     "type": "timeseries",
     "description": "The status history of cluster ConfigNodes",
     "gridPos": { "h": 6, "w": 9, "x": 7, "y": 2 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "node_num{type=\"ConfigNode\", instance=~\"$instance\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "DataNode Status $instance",
     "type": "timeseries",
     "description": "The status history of cluster DataNodes",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "node_num{type=\"DataNode\", instance=~\"$instance\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "SchemaRegion Distribution $instance",
     "type": "timeseries",
     "description": "The number of SchemaRegions in each DataNode",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "region_num_in_data_node{type=\"SchemaRegion\", instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "SchemaRegionGroup Leader Distribution $instance",
     "type": "timeseries",
     "description": "The number of SchemaRegionGroup leadere in each DataNodes",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "region_group_leader_num_in_data_node{type=\"SchemaRegion\", instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "DataRegion Distribution $instance",
     "type": "timeseries",
     "description": "The number of DataRegions in each DataNode",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "region_num_in_data_node{type=\"DataRegion\", instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "DataRegionGroup Leader Distribution $instance",
     "type": "timeseries",
     "description": "The number of DataRegionGroup leaders in each DataNode",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "region_num_in_data_node{type=\"DataRegion\", instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Partition Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SchemaRegionGroup Count $instance",
     "type": "timeseries",
     "description": "The number of SchemaRegionGroups in each Database",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "region_group_num_in_database{type=\"SchemaRegion\", instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "DataRegionGroup Count $instance",
     "type": "timeseries",
     "description": "The number of DataRegionGroups in each DataNode",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "region_group_num_in_database{type=\"DataRegion\", instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "SeriesSlot Count $instance",
     "type": "timeseries",
     "description": "The number of SeriesSlots in each Database",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "series_slot_num_in_database{instance=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "DataRegion Status $instance",
     "type": "timeseries",
     "description": "The status history of cluster DataRegions",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "region_num{type=\"DataRegion\", instance=~\"$instance\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "SchemaRegion Status $instance",
     "type": "timeseries",
     "description": "The status history of cluster SchemaRegions",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "region_num{type=\"SchemaRegion\", instance=~\"$instance\"}",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ratis Stage Time $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ConfigRegion_ratis_log_worker_appendEntryLatency_seconds_sum{instance=~\"$instance\"}[1m])/rate(ConfigRegion_ratis_log_worker_appendEntryLatency_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "appendEntryLatency"
      },
      {
       "expr": "rate(ConfigRegion_ratis_server_follower_append_entry_latency_seconds_sum{instance=~\"$instance\"}[1m])/rate(ConfigRegion_ratis_server_follower_append_entry_latency_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "followerAppendEntryLatency"
      },
      {
       "expr": "rate(ConfigRegion_ratis_consensus_write_seconds_sum{instance=~\"$instance\", stage=\"writeStateMachine\"}[1m]) / rate(ConfigRegion_ratis_consensus_write_seconds_count{instance=~\"$instance\", stage=\"writeStateMachine\"}[1m])",
       "legendFormat": "writeStateMachine"
      },
      {
       "expr": "rate(ConfigRegion_ratis_server_clientWriteRequest_seconds_sum{instance=~\"$instance\"}[1m])/rate(ConfigRegion_ratis_server_clientWriteRequest_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "clientWriteRequest"
      }
     ]
    },
    {
     "title": "Write Log Entry $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ConfigRegion_ratis_log_worker_queueingDelay_seconds_sum{instance=~\"$instance\"}[1m]) / rate(ConfigRegion_ratis_log_worker_queueingDelay_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "queueingDelay"
      },
      {
       "expr": "rate(ConfigRegion_ratis_log_worker_enqueuedTime_seconds_sum{instance=~\"$instance\"}[1m]) / rate(ConfigRegion_ratis_log_worker_enqueuedTime_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "enqueuedTime"
      },
      {
       "expr": "rate(ConfigRegion_ratis_log_worker_writelogExecutionTime_seconds_sum {instance=~\"$instance\"}[1m]) / rate(ConfigRegion_ratis_log_worker_writelogExecutionTime_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "writelogExecutionTime"
      },
      {
       "expr": "rate(ConfigRegion_ratis_log_worker_flushTime_seconds_sum{instance=\"$instance\"}[1m]) / rate(ConfigRegion_ratis_log_worker_flushTime_seconds_count{instance=\"$instance\"}[1m])",
       "legendFormat": "flushTime"
      }
     ]
    },
    {
     "title": "Remote / Local Write Time $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ConfigRegion_ratis_consensus_write_seconds_sum{instance=~\"$instance\", stage=\"writeLocally\"}[1m]) / rate(ConfigRegion_ratis_consensus_write_seconds_count{instance=~\"$instance\", stage=\"writeLocally\"}[1m])",
       "legendFormat": "{{stage}}"
      },
      {
       "expr": "rate(ConfigRegion_ratis_consensus_write_seconds_sum{instance=~\"$instance\", stage=\"writeRemotely\"}[1m]) / rate(ConfigRegion_ratis_consensus_write_seconds_count{instance=~\"$instance\", stage=\"writeRemotely\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Remote / Local Write QPS $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ConfigRegion_ratis_consensus_write_seconds_count{instance=~\"$instance\", stage=\"writeLocally\"}[1m])",
       "legendFormat": "{{stage}}"
      },
      {
       "expr": "rate(ConfigRegion_ratis_consensus_write_seconds_count{instance=~\"$instance\", stage=\"writeRemotely\"}[1m])",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "RatisConsensus Memory $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ConfigRegion_ratis_log_worker_closedSegmentsSizeInBytes{instance=~\"$instance\"}",
       "legendFormat": "closedSegmentsSizeInBytes"
      },
      {
       "expr": "ConfigRegion_ratis_log_worker_openSegmentSizeInBytes{instance=~\"$instance\"}",
       "legendFormat": "openSegmentSizeInBytes"
      }
     ]
    }
   ]
  }
 ]
}